args: !!python/object/new:utils.config.CfgNode
  dictitems:
    bert_type: ./lib/BiomedVLP-CXR-BERT-specialized
    device: 1
    image_size:
    - 224
    - 224
    lr: 0.0003
    max_epochs: 100
    min_epochs: 20
    model_save_filename: medseg_location
    model_save_path: ./save_model
    patience: 20
    project_dim: 768
    test_csv_path: ./data/QaTa-COV19-v2/prompt/test.csv
    test_root_path: ./data/QaTa-COV19-v2/Test
    text_mode: location
    train_batch_size: 16
    train_csv_path: ./data/QaTa-COV19-v2/prompt/train.csv
    train_root_path: ./data/QaTa-COV19-v2/Train
    valid_batch_size: 8
    vision_type: ./lib/convnext-tiny-224
